# Generated by Django 6.0.5 on 2026-05-30 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeregistrationworkforce',
            old_name='empid',
            new_name='empno',
        ),
    ]
