# Generated by Django 6.0.5 on 2026-05-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='empno',
            field=models.CharField(default='', max_length=200),
        ),
    ]
