# Generated by Django 6.0.5 on 2026-06-10 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.projectattendance'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='project_name',
            field=models.CharField(blank=True, default='NAN', max_length=500),
        ),
    ]
