# Generated by Django 6.0.5 on 2026-06-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_attendance_project_attendance_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
