# Generated by Django 6.0.5 on 2026-06-12 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_attendance_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.projects'),
        ),
    ]
