# Generated by Django 6.0.5 on 2026-06-19 10:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_attendance_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViolationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='projectemployee',
            name='role',
            field=models.CharField(choices=[('Supervisor', 'Supervisor'), ('Employee', 'Employee')], default='Employee', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='projectemployee',
            unique_together={('project', 'employee')},
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empno', models.CharField(max_length=200)),
                ('violation_date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=500)),
                ('evidence', models.FileField(blank=True, upload_to='violations/evidence/')),
                ('raised_by_empno', models.CharField(max_length=200)),
                ('reviewed_by_empno', models.CharField(blank=True, max_length=200)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_remarks', models.TextField(blank=True)),
                ('penalty', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='myapp.employeeregistrationworkforce')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='myapp.projectattendance')),
                ('violation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.violationtype')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empno', models.CharField(max_length=200)),
                ('direction', models.CharField(choices=[('SUPERVISOR_TO_EMP', 'Supervisor → Employee'), ('EMP_TO_SUPERVISOR', 'Employee → Supervisor')], max_length=20)),
                ('sent_by_empno', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=300)),
                ('document_type', models.CharField(choices=[('Warning Letter', 'Warning Letter'), ('Show Cause', 'Show Cause'), ('Contract', 'Contract'), ('Payslip', 'Payslip'), ('Medical Certificate', 'Medical Certificate'), ('Leave Form', 'Leave Form'), ('General', 'General'), ('Other', 'Other')], default='General', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='project_documents/')),
                ('status', models.CharField(choices=[('Sent', 'Sent'), ('Acknowledged', 'Acknowledged')], default='Sent', max_length=20)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_documents', to='myapp.employeeregistrationworkforce')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='myapp.projectattendance')),
                ('related_violation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='myapp.violation')),
            ],
        ),
    ]
