# Generated by Django 5.2.14 on 2026-05-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_faceenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='checkin_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='checkin_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='checkout_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='checkout_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
