# Generated by Django 6.0.5 on 2026-06-19 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_violationtype_projectemployee_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdocument',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='myapp.projects'),
        ),
        migrations.AlterField(
            model_name='projectemployee',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.projects'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='myapp.projects'),
        ),
    ]
