# Generated by Django 5.2.14 on 2026-05-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_attendance_checkin_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='checkin_place',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='checkout_place',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
