# Generated by Django 5.2.14 on 2026-05-26 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_attendance_checkin_place_attendance_checkout_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeregistrationworkforce',
            old_name='empno',
            new_name='empid',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='empno',
            new_name='empid',
        ),
    ]
