# Generated by Django 6.0.5 on 2026-06-25 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_projectdocument_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectattendance',
            name='geozone',
        ),
        migrations.RemoveField(
            model_name='projectattendance',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='projectattendance',
            name='site_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectattendance',
            name='site_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.projectattendance'),
        ),
        migrations.AlterField(
            model_name='projectattendance',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='projectattendance',
            name='siteaddress',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='myapp.projectattendance'),
        ),
        migrations.AlterField(
            model_name='projectemployee',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.projectattendance'),
        ),
        migrations.AlterField(
            model_name='violation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='myapp.projectattendance'),
        ),
    ]
