# Generated by Django 5.2.14 on 2026-05-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_empno_employeeregistrationworkforce_empid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='empid',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
