# Generated by Django 6.0.5 on 2026-06-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_projectattendance_geozone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('projectname', models.CharField(max_length=500)),
                ('projectcode', models.CharField(max_length=500)),
                ('currentsupervisor', models.CharField(max_length=500)),
                ('newsupervisor', models.CharField(max_length=500)),
                ('handoverdate', models.DateField(blank=True, null=True)),
                ('handoverperiod', models.CharField(max_length=500)),
                ('handoverreason', models.CharField(max_length=500)),
            ],
        ),
    ]
