# Generated by Django 6.0.5 on 2026-06-27 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_projecthandover'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Permanent', 'Permanent'), ('Temporary', 'Temporary')])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('empname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employeeregistrationworkforce')),
                ('projectname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.projectattendance')),
            ],
        ),
    ]
