# Generated by Django 6.0.5 on 2026-06-30 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_projectworker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectworker',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='projectworker',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='projectworker',
            name='type',
        ),
        migrations.AddField(
            model_name='projectworker',
            name='role',
            field=models.CharField(choices=[('1', 'Supervisor'), ('0', 'Worker')], default='0', max_length=1),
        ),
    ]
