# Generated by Django 6.0.5 on 2026-06-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_projectworker_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectworker',
            name='role',
            field=models.CharField(choices=[('1', 'Supervisor'), ('0', 'Employee')], default='0', max_length=1),
        ),
    ]
