# Generated by Django 6.0.5 on 2026-06-30 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_projectworker_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectWorkerRoleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('1', 'Supervisor'), ('0', 'Employee')], max_length=1)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employeeregistrationworkforce')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.projectattendance')),
            ],
        ),
    ]
