# Generated by Django 6.0.5 on 2026-06-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_projectworkerrolelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecthandover',
            name='handoverperiod',
            field=models.CharField(blank=True, default='0', max_length=500),
        ),
        migrations.AlterField(
            model_name='projecthandover',
            name='handoverreason',
            field=models.CharField(blank=True, default='Supervisor assignment', max_length=500),
        ),
    ]
