# Generated by Django 6.0.5 on 2026-07-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_projecthandover_handoverperiod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectemployee',
            name='deletestatus',
            field=models.IntegerField(default='0'),
        ),
    ]
