# Generated by Django 6.0.5 on 2026-07-01 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_projectemployee_deletestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectEmployeeRoleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Supervisor', 'Supervisor'), ('Employee', 'Employee')], max_length=20)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.employeeregistrationworkforce')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.projectattendance')),
            ],
        ),
    ]
