name: CI Pipeline

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  basic-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: CI Working
        run: echo "CI Pipeline Working Successfully"